### ISSUE TITLE
Setting up on HPC or local computer

### ISSUE THREAD

**Issue by seminaia** [caizefeng/BayesianOpt4dftu#1]
When I try to set up this on a HPC and my locall machine using' pip install git+https://github.com/caizefeng/BayesianOpt4dftu.git'I get an error that it is missing some files like a  README.rst for a package called pychemia.

**Comment by caizefeng** [comment]
Thank you for reporting this. This appears to be a Python version-dependent wheel build bug. 

Please ensure that you only use Python 3.8 when creating the virtual environment for this package (now clarified in the README)
